---
domain: claude-code-hooks
source_task: 2026-03-15-session-continuity.md
date: 2026-03-15
keywords: ["stop hook", "session memory", "context persistence", "hook lifecycle", "post-stop"]
---

## Extracted Knowledge

**Stop hook constraints:**
- Runs AFTER Claude's final response — cannot re-invoke Claude or inject new context
- Has full filesystem access (read/write) but no conversation history
- Output goes to user as a notification, not back into Claude's context
- Cannot generate a "rich reflection" — only mechanical state from files

**Note-preservation pattern:**
To preserve Claude-authored content across Stop hook runs, match the specific section
with a regex and check if it's still the placeholder:
```js
const m = existing.match(/## Session Notes\n\n([\s\S]*?)(?=\n---|\n## |\s*$)/);
if (m && m[1].trim() && !m[1].trim().startsWith('_Not yet written')) {
  return m[1].trim(); // preserve
}
return null; // use placeholder
```

**Stable vs volatile split for context documents:**
- Stable content (architecture, conventions, file paths): rarely changes, ~150 lines max,
  load at session start
- Volatile content (in-flight tasks, recent completions, session decisions): changes every
  session, regenerated by hook, ~50-80 lines
- Mixing them in one file causes size inflation that hits the 200-line effective limit

**Context rot finding (from research):**
- All frontier models degrade with longer context (empirically measured)
- U-shaped attention (start + end bias) breaks down above 50% context fill
- Claude Code's 200-line MEMORY.md cutoff exists for this reason
- Keep always-loaded context under ~150 lines; put detail in separately-loaded files

**What the Stop hook CAN generate automatically (from files):**
- Open task list (from workflows/tasks/)
- Recent completions (from workflows/done/ sorted by name)
- Version number (from VERSION file)
- Timestamp

**What requires Claude to write manually:**
- Key decisions and rationale
- What to pick up next
- Architecture nuance that isn't captured in file names

## Proposed Skill Content

A `claude-code-hooks` skill would cover:
- Hook lifecycle: when each hook runs, what inputs it receives, what output it can produce
- Stop hook specific: filesystem-only, no conversation access, can't reinvoke Claude
- PreToolUse blocking: exit code + JSON output format for blocking decisions
- PostToolUse patterns: detecting specific file writes by matching path patterns
- Platform-awareness: detecting .claude vs .cursor vs .github in __dirname
- CommonJS requirement: why .cjs not .js (package.json type:module compatibility)
