---
domain: seo-indexing
source_task: 2026-05-18-fix-probbrain-sitemap-filter-unpublished.md
date: 2026-05-18
keywords: ["sitemap", "google search console", "Crawled - currently not indexed", "URL inspection", "draft content", "noindex", "robots meta", "thin content", "programmatic SEO"]
---

## Extracted Knowledge

### "Submitted N indexed 0" + "Crawled - currently not indexed" is a quality verdict, not a deliverability bug

When GSC's sitemap report says `submitted=N indexed=0` and per-URL inspection shows `coverageState: Crawled - currently not indexed` (verdict NEUTRAL, pageFetchState SUCCESSFUL, INDEXING_ALLOWED), Google has actively chosen not to put the pages in its index. The crawl succeeded — the pages just failed Google's quality filter.

Common triggers:
- Templated/programmatic pages at scale on a new domain with no external link authority.
- Self-labeled "draft" / "not published" / "internal" content reachable via sitemap or RSS.
- Thin content where the unique-info-per-page is small (small numerical or text deltas against a shared template).
- Duplicate or near-duplicate content across `www.` and apex variants both serving 200 OK.

Don't try to "fix" the crawl pipeline. Fix the content signal: stop sending Google to drafts; consolidate hostname; differentiate page bodies.

### Audit pattern: GSC API for "which pages, which verdict, which canonical"

The `searchconsole.v1.urlInspection().index().inspect()` API call against `sc-domain:<host>` returns per-URL state Google didn't reveal in the dashboard. Useful fields:

```python
res = svc.urlInspection().index().inspect(body={
    "inspectionUrl": url, "siteUrl": "sc-domain:probbrain.com",
}).execute()
idx = res["inspectionResult"]["indexStatusResult"]
# idx["verdict"]: PASS | NEUTRAL | PARTIAL | FAIL
# idx["coverageState"]: "Submitted and indexed" | "Crawled - currently not indexed" |
#                       "URL is unknown to Google" | "Redirect error" | ...
# idx["pageFetchState"]: SUCCESSFUL | REDIRECT_ERROR | PAGE_FETCH_STATE_UNSPECIFIED | ...
# idx["googleCanonical"] vs idx["userCanonical"] — divergence = Google chose a different canonical
# idx["referringUrls"] — empty list means no internal links Google could find
```

Inspect ~10 representative URLs (homepage + each section + a few deep pages). Pattern of verdicts is the diagnosis. E.g. "homepage PASS, all section pages NEUTRAL/crawled-not-indexed, all deep pages URL-unknown" → site is fine technically, content/authority filter is rejecting everything past the homepage.

### Recognizing LLM-agent traffic in GSC query reports

GSC may show non-zero impressions with zero clicks and zero recognizable human queries. Telltale signs of LLM web-search bots (Perplexity, SearchGPT, Bing Copilot, Claude's search tool):

- Long boolean queries with `-site:reddit.com -site:x.com -site:youtube.com -site:tiktok.com` suffixes.
- Multi-comma feature/keyword stuffing like `latest ai news hugging face github openai anthropic google deepmind`.
- Date-anchored queries: `... since:2026-05-01`, `... last 7 days`, `... may 2026`.
- 0% CTR across the board, average position 1–20.

These are AI-agent search queries, not human users. The site is visible to LLM ecosystems but invisible to actual Google Search users. Don't conflate the two — fixing Google indexing won't change agent-bot traffic, and vice versa.

### Don't ship a generator change you can't iterate on — keep the .xml editable

If the sitemap is regenerated by a script on every build, editing only the output file is fragile (next run undoes your filter). But editing the generator commits to a permanent filtering policy that may not be the right call yet. Pragmatic path on first iteration:

1. Edit the output `.xml` directly to ship the immediate fix.
2. Document the filter rule in the task `Outcome` so it's traceable.
3. Defer the generator-level change until the filter rule is confirmed correct (e.g., after seeing GSC re-index results).

This preserves the option to refine the rule (e.g., "also exclude PENDING signals older than 90 days") before baking it into code.

### Top-level filter for "what belongs in the sitemap"

A sitemap is a list of pages you want Google to index and rank for. Include only pages that:
- Return 200 OK (no redirects from sitemap-listed URLs).
- Have unique, substantive content.
- Are linked from `/` or from one short hop away.
- Are "ready" content — no drafts, no internal-only, no paper-traded test data, no preview/staging.

Programmatic pages with status fields like `NOT_PUBLISHED` / `SHADOW` / `DRAFT` / `PENDING-INTERNAL` should be filtered at sitemap-generation time by reading each file's status marker. The Status marker can be detected by regex from the rendered HTML (`/Status:\s*([A-Z_]+)/`) when there's no separate metadata file.

### `www.` + apex both serving 200 = duplicate site to Google

If both `https://probbrain.com/` and `https://www.probbrain.com/` return HTTP 200 with the same content, Google sees two copies of the site. Authority is split, indexing is suppressed. The fix is a 301/308 redirect from one hostname to the other (pick apex or www, doesn't matter which, just commit).

On Vercel: project Settings → Domains → on the non-preferred hostname row, click ⋯ → Edit → "Redirect to..." → pick the other hostname → save. Verify with `curl -sI https://www.host/ | grep -iE "^(HTTP|location)"` — should see `308` + `location:` to the chosen canonical.

GSC's `referringUrls` field on the homepage often reveals this: if your apex domain's homepage shows `https://www.host/sitemap.xml` as a referrer, the www subdomain has its own sitemap and Google found it.

## Proposed Skill Content

An `seo-indexing` skill should activate on prompts mentioning Google Search Console, sitemap.xml, "not indexed", "crawled but not indexed", site visibility, organic traffic drops, robots.txt, canonical tags.

It should teach:

1. **Diagnose "submitted N indexed 0"** as a content-quality verdict, not a pipeline bug. Inspect ~10 URLs via the URL Inspection API to map the failure pattern.
2. **Read GSC queries for LLM-agent traffic** vs human search — boolean queries + `-site:` suffixes + 0% CTR + agent-style feature stuffing.
3. **Filter sitemap by content status** before committing generator changes — edit the .xml output once, validate, then bake into the generator.
4. **Consolidate www/apex** with a 308/301 — both serving 200 is the most common silent duplicate-content trap.
5. **`Status: NOT_PUBLISHED` in meta descriptions** is content saying "ignore me" to Google — fix by removing the leak or by making those pages noindex.
